//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitenessApp.DAL.DbScheme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.Guid> ImageId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Image Image { get; set; }
    }
}
