//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitenessApp.DAL.DbScheme
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomLoad
    {
        public System.Guid Id { get; set; }
        public Nullable<int> CustomSeries { get; set; }
        public string CustomIteration { get; set; }
        public string LoadName { get; set; }
        public Nullable<System.Guid> TrainingId { get; set; }
        public Nullable<System.Guid> TrainingTemplateId { get; set; }
    
        public virtual Load Load { get; set; }
        public virtual Training Training { get; set; }
        public virtual TrainingTemplate TrainingTemplate { get; set; }
    }
}
