//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitenessApp.DAL.DbScheme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Training()
        {
            this.CustomLoads = new HashSet<CustomLoad>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Aim { get; set; }
        public string GenderCategory { get; set; }
        public string Complexity { get; set; }
        public Nullable<int> WeekDuration { get; set; }
        public Nullable<int> DaysPerWeek { get; set; }
        public Nullable<double> TrainingDuration { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public Nullable<System.DateTime> DateOfTraining { get; set; }
        public string Status { get; set; }
        public string CustomerId { get; set; }
        public string CoachId { get; set; }
        public string ManagerId { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomLoad> CustomLoads { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
